### ISSUE TITLE
mamba 0.24.0 and conda 4.13.0

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/mamba-feedstock#156]
### Comment:

@wolfv Did you mean to disallow mamba 0.24.0 and conda 4.13.0?

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/274/files#diff-562be9a7a061c064fe4ad276374912f7928d706ac1b5accf3216d1e64dee5312R1533

I thought 0.24.0 is compatible with 4.13.0?

If not, it is causing some really strange issues where users with:

mamba 0.22.1 installs, that ask to update all their packages, will update to 4.13.0 and then have a situation where they cannot use mamba.

If it is compatible, maybe lets trigger a new build number and get things back to a working state?

**Comment by hmaarrfk** [comment]
https://github.com/mamba-org/mamba/issues/1706#issuecomment-1145432651

**Comment by isuruf** [comment]
It should be allowed. PRs welcome
