### ISSUE TITLE
mamba and conda>=4.8

### ISSUE THREAD

**Issue by naumenko-sa** [conda-forge/mamba-feedstock#21]
Hello!

Thanks for supporting mamba!

Is there a reason why conda version is pinned to <4.8?
https://github.com/conda-forge/mamba-feedstock/blob/2de1e842dfacc8e7be92ea4cfa86acfbeb0c2c7d/recipe/meta.yaml#L29

Could this limitation be removed to use mamba with conda >=4.8?

Sergey

**Comment by wolfv** [comment]
I tested locally and I think the limitation can be lifted indeed. Do you want to make a PR?
