### ISSUE TITLE
Latest mamba (1.5.6) not compatible with conda 24.*

### ISSUE THREAD

**Issue by analog-cbarber** [conda-forge/mamba-feedstock#210]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

conda 24.1.1 was recently released on conda-forge but the latest version of mamba (1.5.6) pins the conda version to the range ` >=23.11,<23.12` so it is not possible to install the latest conda without uninstalling mamba.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jaimergp** [comment]
xref https://github.com/mamba-org/mamba/pull/3191 & https://github.com/conda-forge/mamba-feedstock/pull/208

**Comment by jaimergp** [comment]
Fixed by #217
