### ISSUE TITLE
libiconv.so.2 missing

### ISSUE THREAD

**Issue by msarahan** [conda-forge/mamba-feedstock#60]
Ubuntu 20.04 (regolith) can't run mamba. Ends up with 

```
Traceback (most recent call last):
  File "/home/msarahan/miniconda3/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/home/msarahan/miniconda3/lib/python3.7/site-packages/mamba/mamba.py", line 43, in <module>
    import mamba.mamba_api as api
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory
```

This probably indicates that libiconv was linked as a dependency at some point in the stack, but I don't see it in any of the recipes for mamba, libsolv, or pybind11. libiconv on linux is supposed to come from the compiler toolchain, not the libiconv package.

**Comment by wolfv** [comment]
thanks for opening the bug report! It's hopefully fixed with https://github.com/conda-forge/mamba-feedstock/pull/61 although I am still unsure what happened. 
It might be the new build of curl that isn't linking iconv anymore for some reason...
