### ISSUE TITLE
mamba for osx-arm64

### ISSUE THREAD

**Issue by FelixMoelder** [conda-forge/mamba-feedstock#84]
As micromamba already exists as osx-arm64 package I'm wondering if there are any issues preventing mamba to be build for that architecture, too.

I've tried performed `conda build` for `mamba` locally and the recipe just works fine.
So, can we expect a conda-forge build any time soon?

**Comment by wolfv** [comment]
feel free to put it in the migrator on https://github.com/conda-forge/conda-forge-pinning-feedstock/

**Comment by wolfv** [comment]
thanks @FelixMoelder
